### ISSUE TITLE
Build failed after upgrading storybook-chromatic from 2.2.2 to 3.0.0

### ISSUE THREAD

**Issue by hongbo-miao** [chromaui/storybook-chromatic#4]
My [.travis.yml](https://github.com/Hongbo-Miao/hongbomiao.com/blob/master/.travis.yml#L33-L35) looks like this 

```
if [[ $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]]; 
  yarn run chromatic
fi
```

The [travis log](https://travis-ci.com/Hongbo-Miao/hongbomiao.com/jobs/241853285) shows the error

> chromatic info Uploading your built Storybook... 
> chromatic info Uploaded your build, verifying 
> chromatic info Uploading and verifying build (this may take a few minutes depending on your connection) 
> chromatic ERR! ** Chromatic build failed. **
> Please note the session id: 'faa0e973-fe75-466f-8ac4-ab6e9ce5a959'
> contact support@hichroma.com -or- open a support ticket at https://chromaticqa.com
>  
> chromatic ERR! Problems encountered: 
> chromatic ERR! Error: ContentLoadEvent timed out 
> error Command failed with exit code 255.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> The command "if [[ $TRAVIS_PULL_REQUEST_SLUG != $TRAVIS_REPO_SLUG ]]; then
>   yarn run chromatic
> fi
> " exited with 255.

Seems like a breaking change, but I cannot find any document change at https://docs.chromaticqa.com/setup_ci

Any guide will be helpful, thanks!

**Comment by hongbo-miao** [comment]
https://travis-ci.com/Hongbo-Miao/hongbomiao.com/builds

Interesting, the build (upgrading storybook-chromatic from 2.2.2 to 3.0.0) #686 failed
But next build #688 (using storybook-chromatic 3.0.0) succeed.
![image](https://user-images.githubusercontent.com/3375461/66173566-aa6ce900-e605-11e9-9a7c-523f7b35c3b5.png)

**Comment by tmeasday** [comment]
Hi @Hongbo-Miao, thanks for the report. FYI the (the properly open source repository is at https://github.com/chromaui/chromatic-cli)

I've not seen this `ContentLoadEvent` issue before but I suspect it was a temporary network problem, surfacing from JSDOM. It could be that we upgraded to a new version of JSDOM.

I'll close this and open an issue on the other repo, let me know how things shape up.

**Comment by hongbo-miao** [comment]
Got it, thanks, @tmeasday ! BTW, it will be great to point to https://github.com/chromaui/chromatic-cli in the readme. I had a hard time to find the right repo.

**Comment by tmeasday** [comment]
=> https://github.com/chromaui/chromatic-cli/issues/30

**Comment by tmeasday** [comment]
Good point! I updated `package.json` and the `README.md`. Both will update on npm when we publish the next version I guesss.

**Comment by TomGirard1997** [comment]
Hi, Is the bug fixed or is there an alternative to fix this problem actually?

**Comment by tmeasday** [comment]
Hi @TomGirard1997 - are you seeing the `ContentLoadEvent` issue?

AFAIK @Hongbo-Miao simply saw it one time and we assumed it was due to a network blip that wasn't handled particularly well by the package. We were waiting for others to see the same thing on https://github.com/chromaui/chromatic-cli/issues/30.

Are you seeing the problem consistently or just once?
